version: '3'
services: 
    web: 
        build: ./digism
        expose: 
            - "3000"
        volumes:
            - ./digism:/app
        restart: unless-stopped 
    nginx:
        build: ./nginx
        ports:
            - "80:80"
        depends_on: 
            - web
        restart: unless-stopped
